version: '3.8'

services:
  cypress:
    build: .
    image: cypress-test-image
    volumes:
      - /Users/vialiilohoida/Documents/Hillel_Cypress:/e2e
    working_dir: /e2e
    environment:
      - CYPRESS_BASE_URL=https://guest:welcome2qauto@qauto.forstudy.space
    command: cypress run --env CYPRESS_BASE_URL=https://guest:welcome2qauto@qauto.forstudy.space --spec 'cypress/e2e/hillel_tests/homework_4/cy_hm4_tests.cy.js' --browser chrome
